telegram:
  token: ${TELEGRAM_TOKEN}

google_sheets:
  credentials_file: /etc/secrets/credentials.json  # ⬅️ این خط کلیدی است
  spreadsheet_name: ${SPREADSHEET_NAME}

webhook:
  enabled: true
  port: ${PORT}
  url: ${BASE_URL}
  secret_token: ${WEBHOOK_SECRET}
